### ISSUE TITLE
Add overload to of UseSerilog that allows specifying writeToProviders without specifying a lambda first

### ISSUE THREAD

**Issue by davidfowl** [serilog/serilog-extensions-hosting#14]
This seems to be the minimal code one has to write:

```C#
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSerilog((context, env) => { }, writeToProviders: true)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
```

**Comment by nblumhardt** [comment]
Thanks for dropping by! It's not quite the minimum:

```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSerilog((context, lc) =>
                    lc.WriteTo.Console(), writeToProviders: true)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
```

That lambda is where Serilog's logger configuration needs to be assembled, in this ("inline initialization") mode. Without it, as in your example, Serilog won't write logs anywhere. (The second arg is a `LoggerConfiguration`, not the hosting environment.)

There's another overload of `UseSerilog()` that accepts an `ILogger`, but in that model ("early initialization"), because the logger has already been initialized, it's too late for the method to add the necessary `WriteTo.Providers()` call under the hood, and so the user has to create a `LoggerProviderCollection` and call it themselves in this case.

Sharing state between the logger configuration and `UseSerilog()` is the biggest barrier to us having a really smooth early initialization + good DI integration experience. The best I've come up with so far is something like a `ConditionalWeakTable` hack:

```csharp
Log.Logger = new LoggerConfiguration()
    .EnableAspNetCore() // <-- strawman :-)
    .WriteTo.Console()
    .CreateLogger();
```

Under the hood, `EnableAspNetCore()` would create and `WriteTo` a `LateInitSink`, `LoggerProviderCollection`, and equivalents for late binding of enrichers, a minimum level switch etc. 

All of this state would be wrapped up in a single `LateInitLoggerInfo` object, and associated with the `ILogger` in `ConditionalWeakTable`.

`UseSerilog()`, whether accepting an `ILogger` or looking to the static `Log`, would check the CWT and if an `LateInitLoggerInfo` object was present, use that to hook into DI, including `ILoggerProvider`s and so-on.

We could avoid smuggling state in CWT if we were prepared for `EnableAspNetCore()` to set an `out LateInitLoggerInfo` that the user would pass manually between logger setup and `UseSerilog()`, but that's essentially where we sit at present with the somewhat-awkward `LoggerProviderCollection`.

Hope this all makes sense, writing in a bit of a rush, let me know if you're interested in more details on any of the above.

**Comment by nblumhardt** [comment]
#28 (`CreateBootstrapLogger()) moved things along/shifted the cheese enough that I think we can consider this one stale.
