### ISSUE TITLE
.NET Standard 2.1 target makes development pre-releases unusable w/ .NET Framework

### ISSUE THREAD

**Issue by wjrogers** [serilog/serilog-extensions-hosting#33]
I would like to use the new "bootstrap logger" feature in the dev releases, but I noticed it only targets .NET Standard 2.1. Is it possible for this library to keep targeting .NET Standard 2.0?

I maintain an internal library project that provides hosting and logging configuration boilerplate to several application projects, including a few still targeting .NET Framework 4.8. I'm not able to upgrade these legacy projects to .NET 5 yet, and .NET Framework 4.8 is not compatible with .NET Standard 2.1.

**Comment by nblumhardt** [comment]
Thanks for the note, Will. Personally - I'd really love to drop support for older framework versions in this project, since the components it moves with (`Microsoft.Extensions.*`) tend to move forward pretty regularly themselves. Would taking a source drop and recompiling it, until your older projects move forward, be a workable option? Cheers!

**Comment by wjrogers** [comment]
For what it's worth, the latest 5.0.x versions of all the `Microsoft.Extensions.*` packages still have a .NET Standard 2.0 target, and I'm using them happily w/ .NET Framework. I understand the allure of upgrading, though! If you decide to keep the new target framework, I'll just keep using an older version of this library until I can upgrade. Thanks!

**Comment by nblumhardt** [comment]
Thanks for the follow-up 👍

**Comment by nblumhardt** [comment]
@wjrogers we've re-enabled .NET Standard 2.0 support with the 4.1.0 release, it'd be great to hear how this goes for you 👍
