### ISSUE TITLE
Possible Reloadable Logger Issue

### ISSUE THREAD

**Issue by simbaja** [serilog/serilog-extensions-hosting#39]
I've got .netcore31 application (both a generic host and ASP.NET) application where a logger is throwing an exception when using the reloadable logger.  I haven't developed a minimum test case, but it may have to do with static loggers being accessed early in the lifetime.  The pattern is as follows:

1. Create a class with a static logger (private static ILogger<MyType> _log = Log.ForContext<MyType>();
2. Add another static method/property to the class, call a log method (i.e. _log.Debug) in the method.
3. Add a non-static method that calls three log methods (i.e. _log.Debug x3)
3. During services initialization, call the static method
4. Initialize the CreateBootstrapLogger/UseSerilog as normal
5. In the worker, get an instance of the class and call the non-static method.
6. The first log method will succeed, as will the second
7. The third throws an exception, because _cached is somehow null but _frozen is true (so it's trying to directly call the _cached logger)

If I get some time, I'll try to get a minimum reproducible example written, but I'm under some tight work deadlines at the moment.  Hopefully the description above will help find the logic issue.  Presumably, _cached = null and _frozen = true should never happen.

**Comment by nblumhardt** [comment]
It looks like we should probably be publishing the new (hopefully non-`null`) `_cached` here before we publish `_frozen`:

https://github.com/serilog/serilog-extensions-hosting/blob/dev/src/Serilog.Extensions.Hosting/Extensions/Hosting/CachingReloadableLogger.cs#L170

I'm a little suspicious of:

https://github.com/serilog/serilog-extensions-hosting/blob/554019960100a765b5522e4d23452f15073a1cbc/src/Serilog.Extensions.Hosting/Extensions/Hosting/ReloadableLogger.cs#L657

though, since I can't immediately figure out how `newCached` is going to be non-`null` when this method returns; we might actually need to coalesce it with the logger we're ignoring via the `_` discard in the returned tuple.

Needs 👀  :-)

**Comment by nblumhardt** [comment]
Would be great if you're able to share a partial stack trace, and the exception message, @simbaja - thanks!

**Comment by simbaja** [comment]
[SerilogException.zip](https://github.com/serilog/serilog-extensions-hosting/files/6062386/SerilogException.zip)

I think that this is a minimal reproduction of the issue (hopefully it fails on your machine too).  Let me know if anything else would be helpful.

**Comment by nblumhardt** [comment]
Reproduced - thanks! Will update the thread when I have further info.

Best regards,
Nick

**Comment by nblumhardt** [comment]
Version `4.1.1-dev-00058` is now published on NuGet and should resolve the issue. Any chance you can confirm, @simbaja ? I'll queue up a release version if the fix works in your original code.

**Comment by simbaja** [comment]
Confirmed that the fix works in the original code.  Thanks for investigating and resolving!
